services:
  inpx-web:
    build: .
    container_name: inpx-web
    restart: unless-stopped
    ports:
      - "12380:12380"
    environment:
      INPX: /library/fb2.flibusta.lib.rus.ec.7z.inpx
      LIBDIR: /library
      CACHE_DIR: /usr/local/bin/.inpx-web/cache
    volumes:
      - ./library:/library:ro
      - ./data:/usr/local/bin/.inpx-web
